Use copy with binary.
dimitri/pgcopydb pull request #857
Opened 2024-07-31 12:06 UTC by VaibhaveS

2024-07-31 12:56 UTC, dimitri commented
While I like the idea, the main difficulty with it is how to make sure that the source and target Postgres servers are binary compatible? It's very hard to say because it is not well documented; and compile time options will have an impact in that area (e.g. timestamp internal representation can be either `bigint` or `float8`).

Is is possible to use the binary protocol for selected columns, as in the libpq API? Then we could use it only for bytea columns, or a list of data type we know won't be a problem.

Otherwise we can add a new command line option such as `--use-copy-binary` to drive the decision, leaving the compatibility check to the users.

2024-07-31 13:04 UTC, VaibhaveS commented
> 
> Is is possible to use the binary protocol for selected columns, as in the libpq API? Then we could use it only for bytea columns, or a list of data type we know won't be a problem.
> 
I'll check this out.

2024-07-31 13:05 UTC, VaibhaveS commented
Some tests seem to be failing, I guess it's due to the filtering

2024-08-02 13:27 UTC, VaibhaveS commented
The actions are failing due to a weird reason.

2024-08-02 13:52 UTC, dimitri commented
> The actions are failing due to a weird reason.

We are having a look with @hanefi ; the current suspicion is that the old spelling `docker-compose` is not available anymore, the new spelling `docker compose` might need to be used now. I remember trying and failing to implement that transition some time ago, where it was the opposite problem. If that hypotheses explains it, then we should have a fix shortly (enough).

2024-08-02 14:26 UTC, dimitri commented
If you rebase to the current main branch, it should be all good again now.

2024-08-06 09:09 UTC, hanefi reviewed
One minor comment about whitespaces, otherwise looks good.

2024-08-06 09:09 UTC, hanefi commented on src/bin/pgcopydb/cli_clone_follow.c
> +	"  --use-copy-binary			 Use the COPY BINARY format for COPY operations\n" \
```suggestion
	"  --use-copy-binary             Use the COPY BINARY format for COPY operations\n" \
```

Please update documentation files as well.

2024-08-06 10:25 UTC, dimitri approved these changes

2024-08-06 10:42 UTC, dimitri commented
Was about to merge then realized we are missing a long description of the new option in the docs at that place: https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_clone.html#options -- @VaibhaveS can you add that?

2024-08-06 10:42 UTC, dimitri requested changes
Missing option coverage in docs.

2024-08-06 12:47 UTC, dimitri approved these changes

2024-08-06 12:53 UTC, merged